# Generated by Django 4.0 on 2022-01-12 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dailyMunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visited',
            name='date_visited',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
