# Generated by Django 4.0 on 2022-01-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyMunch', '0002_visited_date_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='distance_miles',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='keyword',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.CharField(default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trendy',
            field=models.BooleanField(default=False),
        ),
    ]
