# Generated by Django 4.0 on 2022-01-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyMunch', '0003_alter_profile_delivery_alter_profile_distance_miles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='open_now',
            field=models.BooleanField(default=True),
        ),
    ]
